# Use an official Nginx image as the base image
FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx-redirector.conf /etc/nginx/conf.d/nginx.conf

# Expose ports (80 for HTTP)
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]